### ISSUE TITLE
Error in the last part

### ISSUE THREAD

**Issue by AK51** [thatbrguy/Deep-Stream-ONNX#1]
![IMG_1891 1](https://user-images.githubusercontent.com/8468724/73468560-ee0f0e00-43bf-11ea-8d8e-136a7b3c175c.JPG)
Hi, I am following your procedure but there is an error in the end. Pls see the jpg for details.
1. My login name is nvidia. I think your project is nano. Does it matter?
2. in the make file, I have changed the deepstream path as shown in the jpg
3. I have put the tiny_yolos folder and vids inside the Deep-Stream-ONNX folder, is it correct?
4. I think I have installed the Deep Stream and its SDK, but not 100% sure.

Thanks.
I have the onnx from Azure and I want to import it to deep stream. Output x,y co-ordinates from my webcam for tracking. Thx.

**Comment by thatbrguy** [comment]
Hi @AK51,

- For Question 1: As long as you replace "nano" with your username "nvidia" it should be fine.
- For Questions 2,3,4: Looks like you have installed DeepStream as the command "deepstream-app" is working. After seeing the errors it looks like DeepStream cannot find your ONNX model file. You can place the model folders and videos anywhere as long as you enter their correct paths in the config files. Please try modifying the paths in the config files.
