### ISSUE TITLE
the confidence of the parser is great than 1

### ISSUE THREAD

**Issue by Devinwong** [thatbrguy/Deep-Stream-ONNX#13]
Hi, Thanks for sharing the tiny yolo v2 parser. This is helpful.
I tried to print out all the confidence values generated by the parser. And it turned out that the values were all great than 1.
confidence: 7.283936confidence: 11.239517confidence: 7.362652confidence: 5.226379confidence: 8.131897confidence: 3.605913

Specifically, I added one printf after this line in nvdsparsebbox_tiny_yolo.cpp.
```
bbox.detectionConfidence = maxProb;
printf("confidence: %f", bbox.detectionConfidence);
```

Would this be because that it needs to add a sigmoid with _objectness_?

thanks,
Devin

**Comment by Devinwong** [comment]
I tried to add a sigmoid as
`const float objectness =  1 / (1 + exp(-detections[start_idx + 4 * b_offset]));`

the values became smaller but still great than 1.

confidence: 1.642912confidence: 0.712376confidence: 3.123025confidence: 0.871825confidence: 3.390945confidence: 1.988148confidence: 4.437259confidence: 1.207407confidence: 0.924861confidence: 2.215419confidence: 1.446780confidence: 4.343579confidence: 1.766636confidence: 2.794246confidence: 5.522664confidence: 1.483680confidence: 0.915197confidence: 1.473137confidence: 2.069382confidence: 2.612437confidence: 7.513885confidence: 7.952342confidence: 0.996683confidence: 1.478973

**Comment by Devinwong** [comment]
I added another sigmoid for prob and the result seem correct now. Could you confirm if this is correct?

`float prob = 1 / (1 + exp(-detections[start_idx + (5 + i) * b_offset]));`

0.626570confidence: 0.806243confidence: 0.921216confidence: 0.878939confidence: 0.696558confidence: 0.815379confidence: 0.731442confidence: 0.699247confidence: 0.745769confidence: 0.921216confidence: 0.878939confidence: 0.859899confidence: 0.840521confidence: 0.626570confidence: 0.806243confidence: 0.650634confidence: 0.859899confidence: 0.840521confidence: 0.851459confidence: 0.680879confidence: 0.779993confidence: 0.921216confidence: 0.878939confidence: 0.707593confidence: 0.851459confidence: 0.680879confidence: 0.779993confidence: 0.839996confidence: 0.903294confidence: 0.859899confidence: 0.840521confidence: 0.696558confidence: 0.815379confidence: 0.731442confidence: 0.839996confidence: 0.903294confidence: 0.637030confidence: 0.754010confidence: 0.841435confidence: 0.695338confidence: 0.609001confidence: 0.851459confidence: 0.680879confidence: 0.779993confidence: 0.626570confidence: 0.806243confidence: 0.637030confidence: 0.754010confidence: 0.841435confidence: 0.695338confidence: 0.609001confidence: 0.630002confidence: 0.736211confidence: 0.626124confidence: 0.867710confidence: 0.734691confidence: 0.839996confidence: 0.903294confidence: 0.921216confidence: 0.878939confidence: 0.630002confidence: 0.736211confidence: 0.626124confidence: 0.867710confidence: 0.734691confidence: 0.605274confidence: 0.801314confidence: 0.735071confidence: 0.712632confidence: 0.637030confidence: 0.754010confidence: 0.841435confidence: 0.695338confidence: 0.609001confidence: 0.859899confidence: 0.840521confidence: 0.605274confidence: 0.801314confidence: 0.735071confidence: 0.712632confidence: 0.647575confidence: 0.899475confidence: 0.835349

**Comment by thatbrguy** [comment]
Hello, thanks for bringing up this issue! 

The ONNX model zoo [page](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2) for the Tiny YOLO v2 model refers to this [blog article](https://machinethink.net/blog/object-detection-with-yolo/) on how to parse the output. I think you can also find a link to the source code from which the Tiny YOLO v2 model was obtained from (from the first link I mentioned here). 

Their approach seems different from yours (note that they use softmax somewhere), so I recommend you to check it out (and perhaps some other implementations as well). 

I would like to investigate a bit more deeper into how other implementations are setting probabilities since I am slightly confused right now. Until I get time to fully investigate, i'll keep this issue open and add a note to the readme. Thanks again for informing me about this issue!

**Comment by Devinwong** [comment]
Thanks for the quick turnaround, thatbrguy.
I will take a look into that. :)

**Comment by thatbrguy** [comment]
No problem @Devinwong :)

Btw, I have pushed PR #14 which corrects this issue. If you get the chance, do give it a try and let me know if it works for you!

**Comment by Devinwong** [comment]
thatbrguy, I tried the new fix and it works.
One thing to notice, when I was building the parser binary, the compiler complained that 
`("dims is deprecated. Use inferDims instead"); `in line 435.
 So I changed it to 
`assert (layer.inferDims.numDims == 3);`
which originally was 
`assert (layer.dims.numDims == 3);`

**Comment by thatbrguy** [comment]
Glad to hear that it works :)

With respect to the deprecation notice, I have to check which version of DeepStream raised it. Will look into it later if I get the time. Thanks for the heads up!
