### ISSUE TITLE
Can I use this method running any onnx models in deepstream?

### ISSUE THREAD

**Issue by o98k-ok** [thatbrguy/Deep-Stream-ONNX#16]
Hi, thatbrguy, I want to konw whether this repo can apply in any onnx models. And what should I do for compating my onnx model.
Thank you.

**Comment by thatbrguy** [comment]
Hello @haoguanguan, you cannot use the code directly for any onnx model. You can use this repository as a reference to see how I have used a specific tiny yolo v2 onnx model with deepstream. 

I would recommend you to research online for a more general guide on how to use an arbitrary onnx model with deepstream.
