### ISSUE TITLE
onnx-tensorrt build error

### ISSUE THREAD

**Issue by maponarooo** [thatbrguy/Deep-Stream-ONNX#2]
I had tried compile but ...
where is Protobuf_INCLUDE_DIR?
---------------------------------------------------------------------------------------------
jetson@jetson-nano:~/my-project/onnx-tensorrt/build$ cmake .. \
> -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.0/bin/nvcc \
> -DTENSORRT_ROOT=/usr/src/tensorrt \
> -DGPU_ARCHS="53"
-- The CUDA compiler identification is NVIDIA 10.0.326
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:110 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/jetson/my-project/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/jetson/my-project/onnx-tensorrt/build/CMakeFiles/CMakeError.log".
jetson@jetson-nano:~/my-project/onnx-tensorrt/build$

**Comment by maponarooo** [comment]
I have solved. I'm sorry~~~

apt-get install libprotobuf-dev protobuf-compiler

**Comment by maponarooo** [comment]
I met another build error.... What is it?

jetson@jetson-nano:~/my-project/onnx-tensorrt/build$ make -j4
Scanning dependencies of target gen_onnx_proto
Scanning dependencies of target nvonnxparser_plugin
[  2%] Running gen_proto.py on onnx/onnx.in.proto
[  4%] Building CUDA object CMakeFiles/nvonnxparser_plugin.dir/ResizeNearest.cu.o
[  6%] Building CUDA object CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o
[  8%] Building CUDA object CMakeFiles/nvonnxparser_plugin.dir/Split.cu.o
Processing /home/jetson/my-project/onnx-tensorrt/third_party/onnx/onnx/onnx.in.proto
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx.proto
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx.proto3
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx.pb.h
generating /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx_pb.py
[ 10%] Running C++ protocol buffer compiler on /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx.proto
[ 10%] Built target gen_onnx_proto
[ 12%] Building CXX object CMakeFiles/nvonnxparser_plugin.dir/InstanceNormalization.cpp.o
In file included from /home/jetson/my-project/onnx-tensorrt/InstanceNormalization.hpp:28:0,
                 from /home/jetson/my-project/onnx-tensorrt/InstanceNormalization.cpp:23:
/usr/include/cudnn.h:63:10: fatal error: driver_types.h: No such file or directory
 #include "driver_types.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/nvonnxparser_plugin.dir/build.make:134: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/InstanceNormalization.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/InstanceNormalization.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 14%] Running gen_proto.py on onnx/onnx-operators.in.proto
Processing /home/jetson/my-project/onnx-tensorrt/third_party/onnx/onnx/onnx-operators.in.proto
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx.proto
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx.proto3
Writing /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators.pb.h
generating /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx_operators_pb.py
[ 16%] Running C++ protocol buffer compiler on /home/jetson/my-project/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx.proto
Scanning dependencies of target onnx_proto
[ 18%] Building CXX object third_party/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx_onnx2trt_onnx.pb.cc.o
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu: In function ‘bool is_CHW(const nvinfer1::Dims&)’:
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:40: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                        ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:40: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                        ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:40: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                        ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:99: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                   ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:99: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                   ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:99: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                   ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:158: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                                                                              ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:158: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                                                                              ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:30:158: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
   return (dims.nbDims == 3 &&
                                                                                                                                                              ^   
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu: In member function ‘virtual nvinfer1::Dims ResizeNearestPlugin::getOutputDimensions(int, const nvinfer1::Dims*, int)’:
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:10: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
          ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:10: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
          ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:10: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
          ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:30: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
                              ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:30: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
                              ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:48:30: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     output.type[d] = input.type[d];
                              ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:49:13: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     if( input.type[d] == nvinfer1::DimensionType::kSPATIAL ) {
             ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:49:13: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     if( input.type[d] == nvinfer1::DimensionType::kSPATIAL ) {
             ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
/home/jetson/my-project/onnx-tensorrt/ResizeNearest.cu:49:13: warning: ‘nvinfer1::Dims::type’ is deprecated [-Wdeprecated-declarations]
     if( input.type[d] == nvinfer1::DimensionType::kSPATIAL ) {
             ^~~~
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:211:54: note: declared here
     TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
                                                      ^
[ 20%] Building CXX object third_party/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx-operators_onnx2trt_onnx.pb.cc.o
[ 22%] Linking CXX static library libonnx_proto.a
[ 26%] Built target onnx_proto
CMakeFiles/Makefile2:183: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
jetson@jetson-nano:~/my-project/onnx-tensorrt/build$

**Comment by thatbrguy** [comment]
>Could NOT find Protobuf

I think you would have to install the protobuf package. Unfortunately I do not remember how/where I installed protobuf, but do try installing the package.

**Comment by thatbrguy** [comment]
@maponarooo Closing the issue. Will re-open if you face any other errors.
