### ISSUE TITLE
Yolo v3

### ISSUE THREAD

**Issue by wulixunhua** [thatbrguy/Deep-Stream-ONNX#3]
Hi , The onnx model of yolo v3 can't run deepstream now ？

**Comment by thatbrguy** [comment]
As per the [FAQ](https://github.com/thatbrguy/Deep-Stream-ONNX/blob/master/FAQ.md) the one from the onnx model zoo did not work when I tried using it. I can't comment for any newer versions of the onnx model if they had updated it in the model zoo. You can also try creating your own onnx model of yolo v3 which is compatible with deepstream.
