### ISSUE TITLE
Engine is created all the time while running app

### ISSUE THREAD

**Issue by komal2110** [thatbrguy/Deep-Stream-ONNX#7]
I have observed that the engine is created everytime when running the application although it is saved first time running the app. And creation of engine takes time. 

WARN                 nvinfer gstnvinfer.cpp:515:gst_nvinfer_logger:<primary_gie_classifier> NvDsInferContext[UID 1]:useEngineFile(): Failed to read from model engine file

INFO                 nvinfer gstnvinfer.cpp:519:gst_nvinfer_logger:<primary_gie_classifier> NvDsInferContext[UID 1]:initialize(): Trying to create engine from model

Please help on this. Thank you.

**Comment by thatbrguy** [comment]
Hi @komal2110,

Please try uncommenting line 126 in `config/deepstream_app_custom_yolo.txt` which says
`#model-engine-file=model_b1_fp32.engine` and try replacing `model_b1_fp32.engine` with the path to your engine file. Do let me know if it prevents DeepStream from creating the engine file again.

And yes, in general creation of engine file from scratch will take some time.

**Comment by komal2110** [comment]
Yes this works. It worked for me by providing the absolute path of engine. Thnak you.
