### ISSUE TITLE
deploy Yolact model (ONNX) on jetson nano

### ISSUE THREAD

**Issue by phamquangnam** [thatbrguy/Deep-Stream-ONNX#9]
Hello,

Thanks for your tutorial !.

I tried to run Yolact model on jetson nano. But I dont't know how can I custom parse Yolact model.

Can you help me with some solution?
This is paper of Yolact model: [https://arxiv.org/pdf/1904.02689.pdf](url)

Many thanks !

**Comment by thatbrguy** [comment]
Hello. Did you try to run your model using DeepStream or did you use any other framework/library/SDK? Was your approach similar to the one followed in this repository? If you could share your specific errors then maybe I could suggest some solutions.

**Comment by phamquangnam** [comment]
Hello. Yes, I try to run on DeepStream.

**Comment by phamquangnam** [comment]
Hello,

Yes, I try to run on DeepStream. 
I also looking for some custom parse model (ssd, mask rcnn, faster rcnn) to create .so file for run app on DeepStream, but custom parse code is very diffirent. So I don't know how can I start with Yolact model. :(

**Comment by thatbrguy** [comment]
Sorry for the delayed response. Ah yes writing the parser code might be a bit of a pain for complex models. You can try to see how `NvDsInferParseCustomYoloV2Tiny` is written in this [file](https://github.com/thatbrguy/Deep-Stream-ONNX/blob/master/custom_bbox_parser/nvdsparsebbox_tiny_yolo.cpp) to think about how you can get started. Hope it gives some direction.
